name: Update dev branch
on:
  workflow_run:
    workflows: [Release]
    types: [completed]
    branches: [master]

permissions:
  contents: write

jobs:
  update-dev:
    name: Sync dev with master
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup git user
        uses: fregante/setup-git-user@v2
      - name: Merge changes from 'master' into 'dev'
        run: |
          git checkout master
          git fetch origin
          git checkout dev
          git pull
          git merge origin/master
          git push origin dev